### ISSUE TITLE
that extra js code is mandatory?

### ISSUE THREAD

**Issue by hgsadhrakiya** [alepez/LiveReload-sublimetext3#13]
Hello All,
I am using the sublime text 3.
I completed all the steps that are listed. 
It is not working for me.

So please let me know all the procedure step by step.

I have below questions regarding this:

1. Can we do this without adding that extra JS code to existing code?
2. Does this support for the PHP as well?
3. Is it compulsory to install that .exe for the windows 10 OR just the chrome extension is enough?

Thanks & Regards,
Hitesh

**Comment by alepez** [comment]
Hi Hitesh.
1) you can use liverload without affecting existing code. For this purpose
you can use a browser extension <http://livereload.com/extensions/>
2) php is supported by SimpleReloadPlugin, other file types (like css) are
handled in a smarter way, e.g: injecting css without reloading the page
3) the chrome extension is enough. if you don't want to add extensions to
your browser, you can simply add the javascript to your project (it can be
enabled only in development mode, depending on how your workflow is)

**Comment by hgsadhrakiya** [comment]
Hello @alepez,
Thanks for the instant reply.

Btw, I read some comments over here https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

As per that this extension is not working at the moment.

So Is it true?

**Comment by hgsadhrakiya** [comment]
So, currently I can't make it work by just the extension. Right?
