### ISSUE TITLE
Why is this active in a python file? Or in C++ files?

### ISSUE THREAD

**Issue by fake-name** [alepez/LiveReload-sublimetext3#14]
1. Open a python file. Or a C++ file. Or any file where inserting HTML makes none of the sense.
2. Type "l"
3. Sublime Text offers the autocomplete option "insert livereload script"

I can confirm the  editor language is set to python. Or C++.

Inserting HTML in a python file makes no sense whatsoever.

The plugin should not fire for editor panes that are anything other then HTML (and maybe php, or whatnot).

Possibly relevant:

https://stackoverflow.com/questions/30876395/how-to-allow-a-sublime-text-3-package-for-certain-file-syntax-only

**Comment by alepez** [comment]
Hi @fake-name, if you can provide a patch, I'll be glad to merge your PR. See https://github.com/alepez/LiveReload-sublimetext3/issues/10
